name: Build (lr2oraja-endlessdream)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup build environment
        run: |
          # install jdk 17 for building
          pacman --sync --refresh --sysupgrade --noconfirm jdk17-openjdk

          # enable passwordless sudo
          echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/99-nopasswd
          
          # create build user
          useradd -d /home/builduser -m -G wheel builduser

          # update directory ownership
          chown -R builduser:builduser .
      
      - name: Build package
        run: |
          sudo -u builduser bash -c 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk makepkg --syncdeps --noconfirm -p PKGBUILD.release'
      
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: lr2oraja-endlessdream
          path: '*.pkg.tar.zst'
          if-no-files-found: error
